### ISSUE TITLE
Replace OSCAL data type pages with links to Metaschema datatypes

### ISSUE THREAD

**Issue by aj-stein-nist** [usnistgov/OSCAL-Reference#15]
As reported by @JustKuzya in https://github.com/usnistgov/OSCAL-Reference/issues/6#issuecomment-1677793867, the reference pages still link to internalized OSCAL data types incorrectly after the website migration.

An example link (now incorrect) to a copy of the data types on the OSCAL site is below.

https://pages.nist.gov/OSCAL-Reference/reference/datatypes/#uri-reference

An updated correct example (and all those like it) will point to the correct upstream link, such as the one below.

https://pages.nist.gov/metaschema/specification/datatypes/#uri-reference

**Comment by aj-stein-nist** [comment]
As much of the other work is done, in review, and one is blocked but only queued until I have a PR in a dependency project reviewed, @JustKuzya expressed interest in picking this up in the current sprint.

**Comment by aj-stein-nist** [comment]
@JustKuzya needs help touching up [the branch](https://github.com/JustKuzya/metaschema-xslt/tree/jk/issue-15) to get into a PR-able state. @aj-stein-nist will volunteer to meet with Dmitry after review to get the PR ready.

**Comment by iMichaela** [comment]
@JustKuzya - I am assuming all broken links for all datatypes in the Reference  will be fixed with this issue.

**Comment by aj-stein-nist** [comment]
We are close to finished on this, need to work through and prerequisites in https://github.com/usnistgov/OSCAL-Reference/pull/20.
