### ISSUE TITLE
Options needed for publishing draft/experiment work as a part of DEFINE

### ISSUE THREAD

**Issue by Compton-US** [usnistgov/OSCAL-Reference#19]
For the work that is ongoing in DEFINE on mapping and shared responsibility/CRM, it would be useful for us to publish the draft reference material so that the public can review without generating the content locally.  It would also encourage use of the branches for evaluation and feedback.

I intended to merge draft metaschema code into the prototype-* branches that I created in OSCAL for mapping and CRM.  I'm not particularly attached to the prefix, but these are not exactly feature branches since they may contain multiple features (merges) for consideration.  If we could choose an appropriate prefix to publish automatically as model drafts or experimental branches, it would be very helpful.

Steps:

- [x] Discuss with team and agree to prefix: agreed to `prototype`.
- [x] Adjust [list_revisions.sh](https://raw.githubusercontent.com/usnistgov/OSCAL-Reference/develop/support/list_revisions.sh) to include branches and/or [generate_modeldoc.sh](https://raw.githubusercontent.com/usnistgov/OSCAL-Reference/develop/support/list_revisions.sh) to build branches with the prefix.
- [x] Adjust the GitHub Actions workflow to support [workflow_dispatch](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows) to interactively call the updated code in GitHub Actions and build updated versions of the site
  - [x] Strech goal: perhaps allow to filter that list in the GitHub interface and intentionally add/remove filters not detected by the script?

**Comment by aj-stein-nist** [comment]
@usnistgov/itl-oscal, unless there is a critical risk or objection from someone on the team in the next day, I am going to recommend we move forward with the prefix `prototype-` and get started since the existing DEFINE-sourced branches have that name and it will make the work slightly faster.

**Comment by wendellpiez** [comment]
I like `prototype` as indeed it encompasses anything we might need it to. :+1:

**Comment by aj-stein-nist** [comment]
Given the tentative DEFINE meeting on Thursday, it might be a good idea to handle this today/tomorrow. I may pick this up soon.

**Comment by aj-stein-nist** [comment]
Changes made per review and pairing sessions but still needs final reviews and possible merge. Will move to Sprint 77.
