### ISSUE TITLE
Set up linkchecking

### ISSUE THREAD

**Issue by nikitawootten-nist** [usnistgov/OSCAL-Reference#5]
CI infrastructure should mirror the linkchecker as configured in [OSCAL Pages](https://github.com/usnistgov/OSCAL-Pages)

**Comment by aj-stein-nist** [comment]
@nikitawootten-nist summarized a potential blocker in regards to how `lychee` handles relative links in the model reference page generation. Nikita: can you post a summary of the issue so we can post an upstream issue, whether or not we move forward with adjusting with/against it? Thanks!

**Comment by nikitawootten-nist** [comment]
> Nikita: can you post a summary of the issue so we can post an upstream issue, whether or not we move forward with adjusting with/against it? Thanks!

I'll do you one better. I have a simple fix waiting to be merged now: https://github.com/usnistgov/metaschema-xslt/pull/75

The problem was with a fix I made to the modeldoc pipeline, which, through a sequence of events, caused an extra upwards path traversal (`../`) to be inserted into relative links between reference pages. This problem was handled gracefully by NIST pages and Hugo serve, but Lychee caught it. The above PR fixes this issue and has the side effect of making relative links between pages much cleaner.

**Comment by aj-stein-nist** [comment]
> I'll do you one better. 

I meant regarding the potential bug with `lychee`, I should have been more clear. We talked about it via Element a little so I understand better and I can file without a description here. Thanks again, I appreciate the status update today during standup.
