### ISSUE TITLE
OSCAL-Reference needs a nice landing page.

### ISSUE THREAD

**Issue by Compton-US** [usnistgov/OSCAL-Reference#7]
We already talked about this, but did not see an issue anywhere.  Apologies if duplicated.  The initial page of the OSCAL reference could use a landing page-style format that gives an overview of the content and audience of the site.  We might assume some people will see this as their first encounter with OSCAL and provide a little guidance to the other locations for content.

Also noticed that we need the link set in Settings for the pages URL that displays on the github project.

**Comment by iMichaela** [comment]
@Compton-NIST - I was wondering if we do not need to improve the navigation flow:
[OSCAL Reference tab](https://pages.nist.gov/OSCAL/) [links to] [OSCAL-Reference page](https://pages.nist.gov/OSCAL-Reference/) [links to] [Model Reference](https://pages.nist.gov/OSCAL-Reference/models/) but there is no obvious way from here to go back to this newly proposed [OSCAL-Reference page](https://pages.nist.gov/OSCAL-Reference/) other than the left top title on the navigation bar (that it is not obvious it is a link).

**Comment by nikitawootten-nist** [comment]
@aj-stein-nist offered an alternative solution: make the OSCAL-Reference homepage meta-redirect to the model reference subpage. We can also revert this once there are more "reference types"

**Comment by iMichaela** [comment]
Here is a draft page : https://hackmd.io/@3oiloo_VSrOgO1isWbZTmw/Bk9D1t9j2/edit .  It also contains a suggestion to modify the title of the Model Reference page to Released Specifications since the page lists links  to the documentation for all releases.

**Comment by aj-stein-nist** [comment]
@iMichaela, can we set aside 15 minutes tomorrow to discussion the released specification rename and then move this into a site draft for a review and an eventual merge this week? On the whole, I am happy with what you have drafted so far and moving forward, but want to understand this recommendation more.

**Comment by aj-stein-nist** [comment]
I would still like to discuss tomorrow but I made a provisional copy of the page which includes my implied feedback.

**Comment by iMichaela** [comment]
> I would still like to discuss tomorrow but I made a provisional copy of the page which includes my implied feedback.

@aj-stein-nist  - Sure! I can put something on the calendar

**Comment by aj-stein-nist** [comment]
I will forward this to Sprint 74 and request review from the team, having addressed feedback during review. This is close to done but not quite complete.
